w1=input("enter the first word:")
w2=input("enter the second word:")
w3=input("enter the third word:")
w4=input("enter the forth word:")
motto= " ".join([w1,w2,w3,w4])
day=input("enter the date:")
month=input("enter the month:")
year=input("enter the year:")
date="/".join([day,month,year])
print("the motto is", motto)
print("the date is", date)